# Theme settings
doks:
    baseurl:
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: XTZ-Shots
            image:
        nav:
            - item_name: Mainnet
              item_url: /mainnet-snapshot
            - item_name: Delphinet
              item_url: 'https://midl.dev'
            - item_name: Delphanet
              item_url: '#'
    footer:
        content:
            logo:
                text: XTZ-Shots
                image:
            copyright: Copyright &copy; 2020. - MIDL.Dev <br>All rights reserved.
        social_list:
            - network_name: github
              profile_url: 'https://github.com/midl-dev'
            - network_name: twitter
              profile_url: 'https://twitter.com/midl_dev'
#            - network_name: sphere
#              profile_url: 'https://midl.dev'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
